let lookup = {
  "en": {
    "successful_criteria_label":"Successful Criteria",
    "dimensions_label": "Dimensions",
    "photography_label": "Photography",
    "critical_issues_label": "Critical Issues",
    "score_sub_label": "Score",
    "adequate_image_count_label": "Adequate Image Count",
    "adequate_image_count_desc": "Adequate Image Count should be in between range of 5 to 7",
    "adequate_image_count_how_to": "Make image count should be in between range of 5 to 7",
    "overall_score_sub_label": "Overall Score",
    "recommended_changes_label": "Recommended Changes",
    "multipack_off_model_label": "Multipack should be off model",
    "multipack_off_model_desc": "Multipack should be off model so that it doesn't affect anyone",
    "multipack_off_model_how_to": "Multipack how to",
    "max-image-size_label": "Max Image Size",
    "max-image-size_desc": "Max Image Size should be there or else zoom won't happen efficiently",
    "max-image-size_how_to": "Try to make your image size bigger",
    "min-image-size_label": "Min Image Size",
    "min-image-size_desc": "Min Image Size should be there or else zoom won't happen efficiently",
    "min-image-size_how_to": "Try to make your image size bigger",
    "min-dpi_label": "Minimum DPI",
    "min-dpi_desc": "Minimum DPI requirement should be adhered",
    "min-dpi_how_to": "Fix the minimum DPI with adding more pixels to the image",
    "allowed_image_format_label": "Allowed Image Format",
    "allowed_image_format_desc": "Image Format should be in the allowed format as the platform will reject otherwise",
    "allowed_image_format_how_to": "Make sure to change the format and have it in the desired way",
    "use_sRGB_color_profile_label": "SRGB Color Profile",
    "use_sRGB_color_profile_desc": "SRGB Color Profile should be there",
    "use_sRGB_color_profile_how_to": "SRGB Color Profile should be fixed for the image",
    "square-aspect-ratio_label": "Aspect Ratio",
    "square-aspect-ratio_desc": "Make sure to have the aspect ratio in the correct format",
    "square-aspect-ratio_how_to": "Skew the image to change the aspect ratio and get the desired one",
    "zoom-able-image_label": "High Resolution Zoom",
    "zoom-able-image_desc": "It is recommended to have the height more than 1600px for high resolution zoom",
    "zoom-able-image_how_to": "Increase the height to be more than 1600px",
    "recommended-image-size_label": "Recommended Size for Images",
    "recommended-image-size_desc": "Amazon recommends using 1000px as one of hte dimension in the image.",
    "recommended-image-size_how_to": "One of the dimension must be greater than 1000px",
    "white_background_main_label": "White Background in Main Image",
    "white_background_main_desc": "Main Image must have white background",
    "white_background_main_how_to": "Make the background as white for the main image",
    "white_background_variants_label": "White Background Variants",
    "white_background_variants_desc": "Variant Images must have white background",
    "white_background_variants_how_to": "Make the background as white for the variant images",
    "single_model_in_main_image_label": "Single Model in Main Image",
    "single_model_in_main_image_desc": "Fashion Listing should have a single model in the main image",
    "single_model_in_main_image_how_to": "Make sure the the main image has a single model",
    "product_fill_label": "Product Fill",
    "product_fill_desc": "Product Must Fill 85% of the image",
    "product_fill_how_to": "Make sure the product is being covered in 85% of the image",
    "is_video_present_label": "Video Variant Present",
    "is_video_present_desc": "Video variant is recommended to boost your listing score",
    "is_video_present_how_to": "Please add video variant to the listing"

  }
}

module.exports = {lookup};
